ARG VER
ARG PASS
FROM docker.elastic.co/elasticsearch/elasticsearch:${VER}


# RUN bin/elasticsearch-service-tokens create elastic/fleet-server fleet-token | awk '{print $NF}' > config/service_account_token.txt
