version: "3"

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:${VER}
    command: ./bindmount/make_certs.sh
    user: "0"
    working_dir: /usr/share/elasticsearch
    environment:
      LOG_PASS: ${LOGSTASH_KEY_PASSPHRASE}
    volumes: 
    - 'certs:/certs' 
    - './instances:/usr/share/elasticsearch/bindmount/instances'
    - './make_certs.sh:/usr/share/elasticsearch/bindmount/make_certs.sh'


    ## Make another startup container to create the service token file and load that onto the main containers via a bind mount or something
volumes: 
  certs:
  kibana_config:
