- module: aws
  s3access:
    enabled: true
    var.queue_url: "https://sqs.us-east-1.amazonaws.com/866358680518/filebeatQueue"
    var.access_key_id: ${AK}
    var.secret_access_key: ${SAK}

# - module: aws
#   s3access:
#     enabled: true
#     var.queue_url: https://sqs.myregion.amazonaws.com/123456/myqueue
#     var.credential_profile_name: fb-aws