path.repo: ["/usr/share/elasticsearch/backup"]
discovery.seed_providers: file
network:
  host: "0"

cluster.initial_master_nodes: [ "node-1" ]

xpack:
  security:
    transport:
      ssl:
        enabled: true
        verification_mode: certificate
        certificate_authorities: [certs/ca.crt]
        # key_passphrase: password
        # certificate: in docker-compose
        # key: in docker-compose
    http:
      ssl:
        enabled: true
        certificate_authorities: [certs/ca.crt]
        client_authentication: optional
        # key_passphrase: password
        # certificate: in docker-compose
        # key: in docker-compose
    authc:
      realms:
        pki:
          realm1:
            order: 1
            certificate_authorities: [certs/ca.crt]
        native:
          realm2.order: 2
  license:
    self_generated:
      type: trial
