metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  # reload.period: 10s
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false

setup.kibana:
  host: "https://kibana:5601"
  ssl:
    certificate_authorities: ["${CERTS_DIR}/ca/ca.crt"]

setup.dashboards.enabled: true
setup.template.enabled: true

output.elasticsearch:
  hosts: ["node-1:9200", "node-2:9200", "node-3:9200"]
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/elasticsearch/config/certs/ca/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/config/certs/metricbeat/metricbeat.crt"
  ssl.key: "/usr/share/elasticsearch/config/certs/metricbeat/metricbeat.key"
  ssl.key_passphrase: password

  username: "elastic"
  password: "changeme"