elasticsearch:
  hosts: ["https://node-1:9200", "https://node-2:9200"]
  ssl:
    verificationMode: full
    alwaysPresentCertificate: true
    # keyPassphrase: password
    # certificateAuthorities: [/usr/share/elasticsearch/config/certs/ca.crt]
    # certificate: /usr/share/elasticsearch/config/certs/kibana/kibana.crt
    # key: /usr/share/elasticsearch/config/certs/kibana/kibana.key

server:
  name: kibana
  host: 0.0.0.0
  # ssl:
  #   enabled: true
  #   certificate:
  #   key:
  #   keyPassphrase:

xpack:
  security.enabled: true

enterpriseSearch.host: 'http://enterprise_search:3002'

xpack.fleet.agents.elasticsearch.host: https://node-1:9200